### ISSUE TITLE
Add vertical lines to Manhattan plot

### ISSUE THREAD

**Issue by LTibbs** [kaustubhad/fastman#2]
First, thank you for developing this package. I have GWAS data with > 20 million markers and could not plot it with qqman.

I would like to add vertical lines to my Manhattan plot to indicate specific sites on the genome. This is possible in the qqman package, as discussed in https://github.com/stephenturner/qqman/issues/23. However, when I use abline() after fastman(), no line is drawn on the plot. 

How can I add vertical lines to a Manhattan plot in fastman?

Thank you.

**Comment by soumyasubhraparia** [comment]
Hello. Thank you for using our package.

You can add vertical lines to your Manhattan plot using `abline()` after `fastman()`. Here is an example code which worked at my end.

`png('test.png', width = 10, height = 6, units = 'in', res = 300);  fastman(m)+abline(v=7);  dev.off();`

Please let me know if this works for you.

**Comment by soumyasubhraparia** [comment]
In fact the following code also worked for me.

`png('test.png', width = 10, height = 6, units = 'in', res = 300); fastman(m); abline(v=7); dev.off();`

Please let me know if either of these two works for you.

**Comment by LTibbs** [comment]
Thank you for your reply. Yes, I was able to get add a vertical line with your code. I think the problem was that I was using, for example, abline(v=50), assuming that this line would be placed at base 50 of chromosome 1, as is the case in qqman. However, this does not seem to be the case in fastman and so abline(v=50) was beyond the limits of the figure. Instead, abline(v=7) places a vertical line towards the end of chromosome 6 in my case.

Could you please explain the conversion between the coordinates used in fastman and in abline()? For example, if I wanted to put a vertical line at base 100 on chromosome 10, what value of v would I use in abline()?

**Comment by kaustubhad** [comment]
Hi, sorry for the delay in getting back to you. Are you looking to do such annotations only when displaying a single chromosome? If so, you need to pass the abline value in Mb units, not BP. If you look at the X axis label for such plots, it displays the unit Mb. So, for example, the command below produces a vertical line at location 25 Mb.
png(file="tmp2.png",width=10, height=6, units="in", res=300); fastman(tmp2); abline(v=25); dev.off();

Do you want this functionality in multi-chromosome i.e. typical manhattan plots as well? That would be difficult to accomplish I think, because the locations are appended one after another for subsequent chromosomes.


![tmp2](https://user-images.githubusercontent.com/39866545/174160315-aaaf9a19-e5c1-470f-87fd-e29dd8c3717d.png)

**Comment by LTibbs** [comment]
OK, thanks for letting me know that the line units need to be given in Mb rather than bp units. That answers my question.
